name: Build and Release EXE

# Запускать этот скрипт только при пуше тегов (версий), начинающихся с "v"
on:
  push:
    tags:
      - 'v*'

# Выдаем права скрипту на создание релизов
permissions:
  contents: write

jobs:
  build-and-release:
    # Используем Windows, так как мы собираем .exe
    runs-on: windows-latest 

    steps:
    - name: Скачивание кода из репозитория
      uses: actions/checkout@v4

    - name: Настройка Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven # Ускоряет сборку, кешируя библиотеки

    - name: Сборка проекта через Maven
      run: mvn clean package

    - name: Создание GitHub Release и загрузка EXE файла
      uses: softprops/action-gh-release@v1
      with:
        files: target/ExcelSplitter.exe # Путь к готовому файлу
        generate_release_notes: true    # Автоматически сгенерирует описание релиза
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}